### ISSUE TITLE
Iceberg

### ISSUE THREAD

**Issue by Raindess69** [petyasoft/Blum#10]
Привет, есть похожее приложение в тг на Blum с таким же функционалом но не такое хайповое. Iceberg называется не планировал на него еще сделать софт?

**Comment by petyasoft** [comment]
привет, на гитхабе уже готовые решения есть, поэтому я пас к сожалению

**Comment by Raindess69** [comment]
> привет, на гитхабе уже готовые решения есть, поэтому я пас к сожалению

Поделись ссылкой пожалуйста на репо, а то не нашел был

**Comment by petyasoft** [comment]
[https://github.com/Axcent-ape/IcebergAppBot

> > привет, на гитхабе уже готовые решения есть, поэтому я пас к сожалению
> 
> Поделись ссылкой пожалуйста на репо, а то не нашел был

](https://github.com/Axcent-ape/IcebergAppBot)
