### ISSUE TITLE
ERROR | 'claimBalance'

### ISSUE THREAD

**Issue by QuantumLeap-us** [petyasoft/Blum#2]
![image](https://github.com/petyasoft/Blum/assets/40482494/142f50c2-43d2-4e4a-bfa9-4c8adeebcf04)
Can this error be ignored? I configured the proxy but I don't know if the proxy is working or not.

**Comment by petyasoft** [comment]
try downloading the software again, I rolled back the version to a more working one,but now errors can still occur, but this is not my fault, as I understand it is due to the heavy load on blum, after the notcoin hype

**Comment by QuantumLeap-us** [comment]
thank you
