### ISSUE TITLE
There is an error

### ISSUE THREAD

**Issue by fiqi732** [petyasoft/Blum#22]
i get the error `18:50:39.50 | ERROR | login | Thread 0 | qi | 'NoneType' object has no attribute 'get'
18:50:44.95 | WARNING | play | Thread 0 | qi | Token is invalid. Refreshing token...` the bot works fine. I just want to ask what is the error?

![Screenshot (25)](https://github.com/petyasoft/Blum/assets/168587624/1658d59f-21d1-4220-9f7d-68e13e6211fe)

**Comment by petyasoft** [comment]
its okey, blum give token with time limit and my soft refresh it
