### ISSUE TITLE
What`s Wrong Sir

### ISSUE THREAD

**Issue by fiqi732** [petyasoft/Blum#23]
![Screenshot (26)](https://github.com/petyasoft/Blum/assets/168587624/db46af66-0657-4552-8b5f-859c632737d3)

**Comment by petyasoft** [comment]
tasks in blum bot not work, try  comment this line (example on screen)
<img width="660" alt="Снимок экрана 2024-07-06 в 14 46 45" src="https://github.com/petyasoft/Blum/assets/168456597/2110c714-e7ba-4582-b21d-c418c88ab3ab">

**Comment by fiqi732** [comment]
@petyasoft Okay now you can, thank you sir
